#!/bin/bash
#This script is run on a fresh install of Raspbian Buster Lite.
#It requires Wi-Fi setup and Internet connectivity  
#It updates the operating system, installs dependancies and fixes bugs
#It installs the following applications: rtl-ais, kalibrate-rtl, aisdispatcher and ais_JSON
#It creates and enables rtl_ais, aisdispatcher and ais_JSON services
#Based on SARCNET AIS Rasp Receiver

echo Setting up AIS for RTL-SDR 

#echo Updating the operating system
sudo apt-get update
sudo apt-get -y upgrade
echo System has been updated!

echo Installing dependancies
sudo apt-get -y install git rtl-sdr librtlsdr-dev libtool libfftw3-dev

echo Fixing a bug in the librtlsdr package configuration file
sudo /bin/sh -c 'cat > /usr/lib/arm-linux-gnueabihf/pkgconfig/librtlsdr.pc <<\EOF
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: RTL-SDR Library
Description: C Utility Library
Version: 0.6.0
Cflags: -I${includedir}/
Libs: -L${libdir} -lrtlsdr
Libs.private: -lusb-1.0
EOF'


echo Installing Kalibrat-RTL
sudo apt install build-essential libtool automake autoconf librtlsdr-dev libfftw3-dev
git clone https://github.com/mikaelpfonseca/kalibrate-rtl
cd kalibrate-rtl
./bootstrap && CXXFLAGS='-W -Wall -O3'
./configure
make
sudo make install


echo Installig AISDISPATCHER
wget https://www.aishub.net/downloads/aisdispatcher_arm_glibc.tar.gz
tar -xzf aisdispatcher_arm_glibc.tar.gz
rm aisdispatcher_arm_glibc.tar.gz
echo Installing aisdispatcher
sudo cp -p ~/aisdispatcher_arm_glibc/aisdispatcher /usr/local/bin



echo Installing RTL-AIS
git clone https://github.com/mikaelpfonseca/rtl-ais
cd rtl-ais
make 
sudo make install
sudo cp -p ~/rtl-ais/rtl_ais /usr/local/bin/



echo Installing ais_JSON
sudo apt-get install python-pip -y
git clone https://github.com/mikaelpfonseca/ais_json
pip install requests
pip install libais
pip install termcolor



echo Creating and enabling an aisdispatcher service
sudo /bin/sh -c 'cat > /etc/systemd/system/aisdispatcher.service <<\EOF
[Unit]
Description=AIS Dispatcher service
After=network.target

[Service]
ExecStart=/usr/local/bin/aisdispatcher -u -G -h 127.0.0.1 -p 10110 -H 54.225.113.225:5322,5.9.207.224:8742,127.0.0.1:5000,178.162.215.175:31547
WorkingDirectory=/home/pi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
EOF'

sudo chmod 644 /etc/systemd/system/aisdispatcher.service

sudo systemctl enable aisdispatcher.service



echo Creating and enabling a RTL-AIS service
sudo /bin/sh -c 'cat > /etc/systemd/system/rtl_ais.service <<\EOF
[Unit]
Description=AIS Dispatcher service
After=network.target

[Service]
ExecStart=/usr/local/bin/rtl_ais -p 0
WorkingDirectory=/home/pi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
EOF'

sudo chmod 644 /etc/systemd/system/rtl_ais.service

sudo systemctl enable rtl_ais.service




echo Creating and enabling a AIS_JSON service
sudo /bin/sh -c 'cat > /etc/systemd/system/ais_JSON.service <<\EOF
[Unit]
Description=AIS JSON Encode
After=network.target

[Service]
ExecStart= /usr/bin/python /home/pi/ais_json/ais_json.py
WorkingDirectory=/home/pi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target

EOF'

sudo chmod 644 /etc/systemd/system/ais_JSON.service

sudo systemctl enable ais_JSON.service


echo Rebooting...
sleep 10
sudo reboot
